bump_version: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: "@kbestak, @FloWuenne"
  description: An analysis pipeline for Molecular Cartography data from Resolve Biosciences.
  force: false
  is_nfcore: true
  name: molkart
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.1.0dev
update: null
lint:
  files_unchanged:
    - .gitignore
